name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Clean npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm install
      - name: List installed packages
        run: npm list --depth=0
      - name: Run linter
        run: npx eslint .
